### ISSUE TITLE
Courtesy fact check result

### ISSUE THREAD

**Issue by patricklodder** [dogecoinfoundation/dogecoin.com#100]
Hi,

https://github.com/dogecoinfoundation/dogecoin.com/blame/main/content/en/dogepedia/articles/dogecoin-developers.md#L14

is incorrect. It lists the wrong people and misses others, and makes it sound like these people, including myself, have been continuously working on this for 8 years, which is simply not true, for anyone listed there.

I suggest to remove all the references to individuals so that you don't risk making people angry that are left out while elevating others to a level they are not due.

Please, let's not rewrite history.

**Comment by tjstebbing** [comment]
Lists of names tends to date really badly and require a lot of maintenance, agree that this can become a headache to 'get right' easier to make it a lot more general.

**Comment by MishaBoar** [comment]
Yeah, I agree too - this needs to be revised and simplified, and revised by developers even after it has been simplified. Similar thing I highlighted for the Roadmap article: https://github.com/dogecoinfoundation/dogecoin.com/pull/31.

**Comment by MishaBoar** [comment]
Also, guys (@qlpqlp, @xanimo), what has happened to the history of the edits done to articles? Why the history now shows this article is derived from the "operating a node" article? 

It is important we can reference the history done in the repository in the past and maintain a reliable history of articles.

**Comment by xanimo** [comment]
> Also, guys (@qlpqlp, @xanimo), what has happened to the history of the edits? Why the history now shows this article is derived from the "operating a node" article? 
> 
> It is important we can reference the history done in the repository in the past and maintain a reliable history of articles, so that content writers can use also that information as a resource.
> 
> For reference for this article, https://github.com/dogecoinfoundation/dogecoin.com/pull/49

i'll have a look shortly, am afk. admittedly haven't worked on this in a couple months so don't know current state/what changes have been made but will see what i can find.

**Comment by qlpqlp** [comment]
> Also, guys (@qlpqlp, @xanimo), what has happened to the history of the edits? Why the history now shows this article is derived from the "operating a node" article?
> 
> It is important we can reference the work done in the repository in the past and maintain a reliable history of articles, so that content writers can use also that information as a resource.
> 
> For reference for this article, #49

Also don't know why, and how can it be possible to remove (still learning how this work in detail lol)
If anyone can explain how can we remover the history of edits or change it will help understand what went wrong :)

**Comment by xanimo** [comment]
> > Also, guys (@qlpqlp, @xanimo), what has happened to the history of the edits? Why the history now shows this article is derived from the "operating a node" article?
> > 
> > It is important we can reference the work done in the repository in the past and maintain a reliable history of articles, so that content writers can use also that information as a resource.
> > 
> > For reference for this article, #49
> 
> Also don't know why, and how can it be possible to remove (still learning how this work in detail lol)
> If anyone can explain how can we remover the history of edits or change it will help understand what went wrong :)

Alright will look into for real today.

**Comment by MishaBoar** [comment]
Guys, on a note - most of the starting articles and stubs were written by me and Richard, there is no need to fix this in this circumstance, and the closed PRs can be followed if any doubt arises. My warning refers mostly to the future, when hopefully many contributors will start pushing their articles and we will need to reference who did what. I was only baffled to see the article was derived from "operating a node" (and thought I had made some mistake myself). Please do not worry.

First iteration should be a baseline upon which others can build and improve upon. In this specific case making the article more generic serves that purpose too.

**Comment by patricklodder** [comment]
Looks like this has been fixed - thanks!
