### ISSUE TITLE
Page layout issue on mobile phones

### ISSUE THREAD

**Issue by deepakoffline** [dogecoinfoundation/dogecoin.com#102]
the website is not looking fine on mobile phones. Just move it right and left, and you will know. Also, the slide show thing moves the page up and down when you are further down the page. There is a lot of gaps between various elements on the mobile layout.
![1](https://user-images.githubusercontent.com/108414342/176459805-528a9eda-5d82-42ae-8c83-4b1198a7dd97.jpeg)
![2](https://user-images.githubusercontent.com/108414342/176459833-c3798f1f-648e-4c76-8a67-aa0cddd3e90c.jpeg)
![3](https://user-images.githubusercontent.com/108414342/176459846-355fe150-8437-44aa-aceb-9a025a4da7c2.jpeg)

**Comment by qlpqlp** [comment]
Fixed on the latest version :)

**Comment by deepakoffline** [comment]
That’s awesome 👏🏼
