### ISSUE TITLE
Original SVG version of Doge logo

### ISSUE THREAD

**Issue by cryptocasinoscc** [dogecoinfoundation/dogecoin.com#108]
As Inevitable requested.
![svg-org-DOGE](https://user-images.githubusercontent.com/98087237/177317749-9a8af9c5-da79-474c-a330-850e095183b6.svg)

**Comment by qlpqlp** [comment]
Much thanks for sharing. Sadly this is not the original. This is a converted version from an PNG file

We still need to find the original :)

**Comment by cryptocasinoscc** [comment]
Here is another one, let's see how it goes dear @qlpqlp :)
![Dogecoin shiba logo](https://user-images.githubusercontent.com/98087237/177320035-8a4b8c65-4f03-4d62-8b78-f6a41bc01b85.svg)

**Comment by Fantoumi** [comment]
![Shiba Inu Dogecoin SVG format](https://user-images.githubusercontent.com/108735588/177322285-211a6480-a376-4c40-a599-7f83aff83764.svg)

**Comment by FaTDooG** [comment]
![2cbabfbe523180ac534952d17a1b07a2](https://user-images.githubusercontent.com/108736037/177323672-d7950fc2-ba7b-459c-81c1-73de14310004.png)

**Comment by CryptoEconomize** [comment]
![clean vector](https://user-images.githubusercontent.com/6612446/177347385-67f70e91-214a-42d0-9682-f68965e02091.svg)

**Comment by qlpqlp** [comment]
Much thanks for everyone helping on trying to find the original one :)
Added now on the new preview :)
