### ISSUE TITLE
feature(page): Legal Page

### ISSUE THREAD

**Issue by exu3** [dogecoinfoundation/dogecoin.com#11]
`/legal` page. Copy should probably be in markdown so it's easy for the translation team to contribute.

<img width="848" alt="Screen Shot 2021-12-03 at 10 19 27 PM" src="https://user-images.githubusercontent.com/72365100/144700058-1cacb521-7051-401f-97c2-b229ef492cb5.png">

**Comment by qlpqlp** [comment]
Will be added soon, have to be reviewed by Jens :)
