### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Maniixer** [dogecoinfoundation/dogecoin.com#110]
Removed background color, changed number colors  
![image](https://pbs.twimg.com/media/FXEzRgWXEAAfuFr?format=jpg&name=large)
having the social icons have a section by itself.
![image](https://pbs.twimg.com/media/FXD9UkLWIAQvTe0?format=jpg&name=large)

**Comment by qlpqlp** [comment]
Much thanks for your feedback :)
I have improved a litle bit on this preview, can you check if its OK to you now?

**Comment by Maniixer** [comment]
yes i like that! much wow!

**Comment by Maniixer** [comment]
@qlpqlp what do you think about this? 
![image](https://user-images.githubusercontent.com/92598085/178437433-60e7508a-df94-45ed-ad41-3985dec7689a.png)
"Getting started" moved to the left so it aligns with the rest.
![image](https://user-images.githubusercontent.com/92598085/178440589-6b7ce0af-c188-48a6-a6c7-a7aeb2f4e3b7.png)

**Comment by qlpqlp** [comment]
Wow, love it 😃❤️❤️❤️

**Comment by qlpqlp** [comment]
Just to say I have applied your suggestions :)
