### ISSUE TITLE
Suggestions for mobile

### ISSUE THREAD

**Issue by alamshafil** [dogecoinfoundation/dogecoin.com#124]
1. Edge padding increase in drop-down menu
![image](https://user-images.githubusercontent.com/36016500/180111219-eb44e228-f676-4316-a1df-3488d4459af7.png)

2. Decrease edge padding on Dogepedia pages
![image](https://user-images.githubusercontent.com/36016500/180111340-2efd9d11-9de6-4239-a13c-901ed4298ec6.png)

3. Minor nit: sub-heading font looks out of place and left-margin
![image](https://user-images.githubusercontent.com/36016500/180111440-77211e13-fa6f-4321-ba49-3873f4a81076.png)

4. Code blocks cut off, maybe word warp of clear indicator.
![image](https://user-images.githubusercontent.com/36016500/180112050-88d09904-51da-4760-8d65-e4851acba103.png)
 
5. Minor nit: Small device screen cause this:
![image](https://user-images.githubusercontent.com/36016500/180112129-105ab8bc-6fc3-48fc-81f4-b05d40d6832d.png)

6. In dark mode homepage has thin margin on the edges (might be hard to see)
![image](https://user-images.githubusercontent.com/36016500/180112231-e49df82e-25af-4492-a682-3884d47b80f3.png)

7. Dark mode social media has white background
![image](https://user-images.githubusercontent.com/36016500/180112282-59cb8788-c238-419e-a060-39adbf86a0a4.png)

8. Spacing here looks off: 
![image](https://user-images.githubusercontent.com/36016500/180112395-15bb9349-858b-4d17-a41a-45156201ea0b.png)

**Comment by Maniixer** [comment]
- add link towards GitHub, also adding all socials links in mobile version in the navbar would be great!

**Comment by Maniixer** [comment]
- for the navbar remove the language and dark/light mode and put them in the dropdown menu.

**Comment by alamshafil** [comment]
This can be closed when #125 is merged.
