### ISSUE TITLE
Wallets Page: Including Open/Closed Source

### ISSUE THREAD

**Issue by MishaBoar** [dogecoinfoundation/dogecoin.com#132]
I think it is important to include in the Wallets page also whether a wallet is closed or open source, exactly as they do on the Bitcoin's website.

I know MyDoge had plans to open up their source code a while ago, but since their app now includes a lot of additional functionality unrelated to basic Dogecoin wallet functionality, this might be unlikely.

I think this is important.

**Comment by qlpqlp** [comment]
I Think this should cover :P https://dogecoin.com/wallets/
I Will close this issue Misha :)
