### ISSUE TITLE
Missing link on how-do-i-get-a-wallet

### ISSUE THREAD

**Issue by qlpqlp** [dogecoinfoundation/dogecoin.com#138]
"Private Key"  link on /how-do-i-get-a-wallet Dogepedia article is missing, showing 404.

https://dogecoin.com/dogepedia/articles/how-do-i-get-a-wallet/

![Screenshot_20220727-104749_Chrome.jpg](https://user-images.githubusercontent.com/5968076/181220967-2c887d25-437d-4b95-8e22-131de9741d61.jpg)

**Comment by MishaBoar** [comment]
Thanks!
