### ISSUE TITLE
In the links of social networks there is a character

### ISSUE THREAD

**Issue by dogtorpicapollo** [dogecoinfoundation/dogecoin.com#144]
A character is displayed in the middle of social media logos
![image](https://user-images.githubusercontent.com/8778712/181598695-11820658-0002-49c2-ba05-30c374c19b67.png)

**Comment by dogtorpicapollo** [comment]
![image](https://user-images.githubusercontent.com/8778712/181599280-82565e89-a1cf-4d04-a6d1-18d06f7e4f7f.png)
In the dark version the social links are seen in a white box

**Comment by alamshafil** [comment]
I have a fix for both of these issues: https://github.com/dogecoinfoundation/dogecoin.com/commit/e4da0400a2382ad600079ec448736c12d1433b3c
