### ISSUE TITLE
Dark Mode Main background color & Social Logo's color change with dark mode. ASSETS AVAILABLE BELOW.

### ISSUE THREAD

**Issue by Maniixer** [dogecoinfoundation/dogecoin.com#147]
I would say having the background color in dark-mode be `#000000` is to strong for the eyes, i would suggest changing the background color more to `#171717`.
![image](https://user-images.githubusercontent.com/92598085/181708604-f62a1f7f-a388-4b28-a1d1-745b068f73b9.png)
![image](https://user-images.githubusercontent.com/92598085/181718151-03f8b08a-726e-45c8-96e7-7d07c91e88aa.png)

ASSETS GREY LOGO'S
Color of Assets `#AAAAAA`
[Grey Social Logos.zip](https://github.com/dogecoinfoundation/dogecoin.com/files/9218144/Grey.Social.Logos.zip)

**Comment by Maniixer** [comment]
![image](https://user-images.githubusercontent.com/92598085/181718549-51f97010-2175-4b90-ad33-c89ad1a7f302.png)

**Comment by qlpqlp** [comment]
Also love the gray assets :)

**Comment by nformant1** [comment]
It looks like there are still two reaminig issues.

There are white bars in each logo and the D has still a white filling:
![image](https://user-images.githubusercontent.com/54002590/188303041-835687b7-32c7-4d54-a89f-ed1e64a833e7.png)

![image](https://user-images.githubusercontent.com/54002590/188303064-9724d40d-e335-483f-92d4-42d90f228f03.png)

Hope this helps!

Best regards
nformant

**Comment by SavPhill** [comment]
This is caused by the class of the a href attribute. When switching to light, it has the opposite effect.

I can help to review the fix, but looking at @qlpqlp approval of the grey assets above, i'm not sure it's necessary anymore.

**Comment by Maniixer** [comment]
@qlpqlp any info on when this will be resolved?

**Comment by qlpqlp** [comment]
Done!, sorry the delay.
