### ISSUE TITLE
style(homepage): wallets

### ISSUE THREAD

**Issue by exu3** [dogecoinfoundation/dogecoin.com#15]
`/#wallets` Needs some love (mainly styles and responsiveness) ✨. Basic skeleton should be on the `redesign` branch. 

<img width="1325" alt="Screen Shot 2021-12-03 at 10 20 08 PM" src="https://user-images.githubusercontent.com/72365100/144700376-b99fde0f-0877-447f-b14b-20814a45096c.png">
<img width="1325" alt="Screen Shot 2021-12-03 at 10 20 27 PM" src="https://user-images.githubusercontent.com/72365100/144700418-e2fc7a14-bda6-4db6-964b-c7bd4610b495.png">

**Comment by qlpqlp** [comment]
This was change on the latest preview and will also be again reviewed in the next days :)
