### ISSUE TITLE
Add Dogecoin and Dogecoin Foundation github links.

### ISSUE THREAD

**Issue by Maniixer** [dogecoinfoundation/dogecoin.com#150]
Let me know if if you want this i will send the assets for both light and dark mode in this issue.

![image](https://user-images.githubusercontent.com/92598085/181765627-3c394f83-3bbb-4bab-8902-e44c503dcf13.png)

SVG ASSETS:
[Github Logo's.zip](https://github.com/dogecoinfoundation/dogecoin.com/files/9222805/Github.Logo.s.zip)

**Comment by Maniixer** [comment]
@qlpqlp should i @ you here? so you would not miss it :p

**Comment by qlpqlp** [comment]
Love the idea :)

**Comment by Maniixer** [comment]
I have updated above comment, the ZIP file is there with the SVG assets in it.

**Comment by qlpqlp** [comment]
I remember one thing, the links is only for social media and not for projects, that's why its not included :)
If you agree also you can close the issue :)

**Comment by Maniixer** [comment]
hmm yeah but something that is bothering me a bit is that i can't find links to those 2 projects, and i really think it would be important to have that. 

maybe having it in the footer is 1 solution but personally i think not many users will find it that way, as its kinda hidden

**Comment by qlpqlp** [comment]
Its on the Wallets Section, for the Core Wallet : 
![image](https://user-images.githubusercontent.com/5968076/184454228-101c4172-2f3c-49f2-9977-5a3c7b94eb8e.png)

**Comment by qlpqlp** [comment]
Will close this issue because there was no more feedback. If needed, reaopen :)
