### ISSUE TITLE
Links are not obvious, especially in Dogepedia

### ISSUE THREAD

**Issue by jwiechers** [dogecoinfoundation/dogecoin.com#153]
Links are very hard (or impossible) to identify in some cases, especially in Dogepedia. This makes it harder to learn and understand context. 
This is true for both light and dark mode.

An example is the link to "Dogecoin Manifesto" on https://dogecoin.com/dogepedia/articles/what-is-dogecoin/

**Comment by qlpqlp** [comment]
See if that is ok to you :)
![image](https://user-images.githubusercontent.com/5968076/182136690-9cba0ec0-de88-4e58-9973-d0fa92af7403.png)
![image](https://user-images.githubusercontent.com/5968076/182136777-f8cf0238-beba-42df-9035-1f551715db7b.png)

**Comment by qlpqlp** [comment]
The yellow part is wen the mouse is over a link

**Comment by Maniixer** [comment]
this is much better imo. you can just remove the `text-decoration: none`
and give it another class name.

![image](https://user-images.githubusercontent.com/92598085/182164068-a5b4d931-86c8-423c-a99d-dca16d99519b.png)

**Comment by qlpqlp** [comment]
I could do that. I removed text decoration do to some issues on some images with href that were showing an "hiffen" character :)
Wafting just fot a feed back from @jwiechers do thoughts :)

**Comment by Maniixer** [comment]
haha yeah i see that ^^ the code is a little messy with classes and css :p

**Comment by qlpqlp** [comment]
Fixed :) https://github.com/dogecoinfoundation/dogecoin.com/pull/175
