### ISSUE TITLE
The reddit icon's text in dark mode is to difficult to read.

### ISSUE THREAD

**Issue by alamshafil** [dogecoinfoundation/dogecoin.com#164]
As written by @xanimo in https://github.com/dogecoinfoundation/dogecoin.com/pull/125#pullrequestreview-1057886667

The reddit icon's text in dark mode is to difficult to read.

> ![image](https://user-images.githubusercontent.com/36016500/182945564-1ad9f073-b4cf-43a6-829c-86d4f2a3aad6.png)
In dark mode, considering the reddit icon's text is dark on dark perhaps we should just make that particular section a bit lighter for legibility purposes?

**Comment by Maniixer** [comment]
I gave a solution for the icon on #147 :p

**Comment by qlpqlp** [comment]
Thanks @alamshafil will review how to add #147 :)
