### ISSUE TITLE
style(homepage): Find out more about Dogecoin

### ISSUE THREAD

**Issue by exu3** [dogecoinfoundation/dogecoin.com#17]
This is the section at the bottom of the homepage.

<img width="1085" alt="Screen Shot 2021-12-03 at 10 44 19 PM" src="https://user-images.githubusercontent.com/72365100/144700504-282c8400-a9bc-4dad-847c-8316573d5b56.png">

**Comment by bellesea** [comment]
Will aim to complete this by 23rd December

**Comment by qlpqlp** [comment]
I think this is already added on the latest preview, so I will close :)
