### ISSUE TITLE
Ledger wallet official website link error

### ISSUE THREAD

**Issue by peng3rock** [dogecoinfoundation/dogecoin.com#176]
[Ledger.md](https://github.com/dogecoinfoundation/dogecoin.com/blob/112736bdae497e58f3330ecff7ae29d7912992b9/content/kr/wallets/Ledger.md) 

The link of ledger wallet points to the official website of trezor wallet.

There is the same error in the webpage.
![image](https://user-images.githubusercontent.com/93751421/184503535-038d1303-743c-402f-8f7a-a4c2ba331178.png)

**Comment by bobdos** [comment]
@qlpqlp 

please have a check for double confirmation. 

many thanks.

**Comment by qlpqlp** [comment]
Yes, the link is worng. I did not realize wen uploading. Will fix ASAP

**Comment by qlpqlp** [comment]
Fixed in this update :)
