### ISSUE TITLE
Proposal to change to the Dogeathon Icon Style

### ISSUE THREAD

**Issue by SavPhill** [dogecoinfoundation/dogecoin.com#222]
Proposal to edit the style of the new Dogeathon menu item, as its background-color is not consistent with usual brand styling of buttons.

![dogeathon before](https://user-images.githubusercontent.com/38789408/189831776-a8704f0a-6599-4ec5-807c-d2d66a9138ae.png)

I have made a PR which corrects this issue below. Please review if it's suitable:

https://github.com/dogecoinfoundation/dogecoin.com/pull/221

**Comment by qlpqlp** [comment]
The color was because of the original banner from Dogeathon :)
