### ISSUE TITLE
Tip: Add download ranking to wallets

### ISSUE THREAD

**Issue by dogtorpicapollo** [dogecoinfoundation/dogecoin.com#228]
Hello friends, 

I've been looking at the download of wallets and I get an idea in my head that asks to promote competitiveness between wallet products.

I think that if the download screen is organized by some type of ranking or user votes it would generate more competition among the wallet creators, I think that the end users of the products would be happier and there would be more competition.

Also add a category where wallets can be organized by newly added

![image](https://user-images.githubusercontent.com/8778712/190469583-d42aa9a0-7350-42d5-a493-bbcbeeba9ace.png)

**Comment by Drael64** [comment]
A filter function is a good idea. Maybe 'multicurrency' for wallets that support other assets. Newly added won't happen often tho and it's not a huge list. 

But downloads would be hard to code I think. You'd need to poll google play, the apple store, and the chrome extension store. Which could break at any time if they change how it works.

**Comment by qlpqlp** [comment]
Love your idea, I could implement something like Dogecoin Voting system using an Doge Address and an value for each wallet that could be easily tracked, but for now we will not add any type ratings on any wallet :)
