### ISSUE TITLE
Some Dogecoin Wallets Missing

### ISSUE THREAD

**Issue by Drael64** [dogecoinfoundation/dogecoin.com#230]
ThorWallet, xDeFi, Coinomi, Exodus are absent from the Wallets list.

They are all self-custody wallets that support dogecoin. Coinomi, Exodus are quite big names in self-custody wallets. ThorWallet and xDeFi support native dogecoin DeFi on Thorchain. xDeFi is a browser extension wallet, the other three are Android and iOS apps.

**Comment by qlpqlp** [comment]
All wallets added. Waiting for merge :)
Added comment on the same request here: https://github.com/dogecoinfoundation/dogecoin.com/issues/231
