### ISSUE TITLE
Wallet proposals-non custodial 

### ISSUE THREAD

**Issue by Alex-long69** [dogecoinfoundation/dogecoin.com#231]
Thorwallet, xDefi, coinonomi, exodus

**Comment by Drael64** [comment]
Hey, I said that too!

**Comment by qlpqlp** [comment]
https://github.com/dogecoinfoundation/dogecoin.com/pull/243

**Comment by qlpqlp** [comment]
https://github.com/dogecoinfoundation/dogecoin.com/pull/244

**Comment by qlpqlp** [comment]
There was an original request here for this same wallets: https://github.com/dogecoinfoundation/dogecoin.com/issues/230
All wallets added. Waiting for merge :)
