### ISSUE TITLE
Dogecoin is a fork of Bellscoin

### ISSUE THREAD

**Issue by zachzwei** [dogecoinfoundation/dogecoin.com#309]
Please update the following statement:
‘ Dogecoin was originally a fork of a cryptocurrency called Luckycoin - itself a fork of Litecoin.’
Found here:

https://dogecoin.com/dogepedia/faq/dogecoin-has-no-developers/

Billy Markus specifically mentions Bellscoin which is a fork of Luckycoin as the direct fork of Dogecoin. 
References:
* https://x.com/billym2k/status/1732424915528417602?s=46
* https://x.com/billym2k/status/1643063317781680131?s=46
* https://www.youtube.com/watch?v=lWxXwZ6abhA&t=419s
* https://x.com/billym2k/status/1735062601548398794?s=46

**Comment by zachzwei** [comment]
> https://github.com/LuckycoinFoundation/Luckycoin/blob/master/src/main.cpp#L846
> 
> vs
> 
> https://github.com/Nintondo/bellscoinV3/blob/main/src/validation.cpp#L1771
> 
> vs
> 
> https://github.com/dogecoin/dogecoin/blob/master/src/dogecoin.cpp#L133
> 
> Sorry, Dogecoin is a fork of Luckycoin, and not Bells.
> 
> This is because in Bells, the prevhash didn't influence the random reward unlike Luckycoin AND Dogecoin, and thus it cannot have been forked from that ❤️

So Billy is lying?
I also this on Reddit:
https://www.reddit.com/r/dogecoin/comments/js2o07/comment/gbwud5u/

Also, why are you referencing a file on Dogecoin where the oldest commit was in 2018. 
Lastly, why did you referenced Bellsv3 instead of the OG one: 
https://github.com/bellscoin/bellscoin/tree/master

**Comment by qlpqlp** [comment]
> > https://github.com/LuckycoinFoundation/Luckycoin/blob/master/src/main.cpp#L846
> > vs
> > https://github.com/Nintondo/bellscoinV3/blob/main/src/validation.cpp#L1771
> > vs
> > https://github.com/dogecoin/dogecoin/blob/master/src/dogecoin.cpp#L133
> > Sorry, Dogecoin is a fork of Luckycoin, and not Bells.
> > This is because in Bells, the prevhash didn't influence the random reward unlike Luckycoin AND Dogecoin, and thus it cannot have been forked from that ❤️
> 
> So Billy is lying? I also saw this on Reddit: https://www.reddit.com/r/dogecoin/comments/js2o07/comment/gbwud5u/ Via this tweet by a Dogecoin Foundation Dev: https://x.com/inevitable360/status/1677596792588828672?s=46
> 
> Also, why are you referencing a file on Dogecoin where the oldest commit was in 2018. Lastly, why did you referenced Bellsv3 instead of the OG one: https://github.com/bellscoin/bellscoin/tree/master

Hello, sorry but @patricklodder is right, my Post on X.com is not entirely correct.

**Comment by zachzwei** [comment]
So there are 2 Dogecoin devs that are saying:
“Billy Markus is lying, that Dogecoin was a fork of Bells.”

Got it.

**Comment by zachzwei** [comment]
If you guys think that is the only reason I am requesting a correction on the main site, “to pump my bags” then you don’t really know who I am. 

I am merely trying to spread awareness and making sure the right information is being shared. Unlike what this revival of Luckycoin is doing.

Isn’t that what this statement is on the site mean?:
“ Let’s fight against the disinformation surrounding Dogecoin! Much wow!”

In any case, I will go ahead and close this. Apologies if I had offended anyone.

**Comment by zachzwei** [comment]
Here is the summary of my research on Bellscoin being forked to create Dogecoin:

1. The Genesis Block message is the same: https://x.com/ZachZwei/status/1862512487868112906
2. The Bellscoin logo on the Dogecoin Client: https://x.com/ZachZwei/status/1862897218107453770
3. AI comparing repos of Luckycoin, Bellscoin and Dogecoin to explain lineage: https://x.com/ZachZwei/status/1863226678740492632

Sources:
main.cpp file for all coins mentioned (oldest versions available):
https://github.com/maxpwr/Luckycoin/blob/master/src/main.cpp
https://github.com/bellscoin/bellscoin/blob/master/src/main.cpp
https://github.com/dogecoin/dogecoin/blob/8b09dc5d711bc0bedefc29c199a79ce39f691558/src/main.cpp


Bellscoin Logo on Dogecoin client (v1.0) video:
https://x.com/ZachZwei/status/1863270288974344270
bitcoin.icns file link:
https://github.com/dogecoin/dogecoin/blob/8b09dc5d711bc0bedefc29c199a79ce39f691558/src/qt/res/icons/bitcoin.icns
