### ISSUE TITLE
re design dogecoin.com

### ISSUE THREAD

**Issue by remigermain** [dogecoinfoundation/dogecoin.com#6]
Hi i have started few days ago a re-design of dogecoin.com  merged with doge foundation  website, is writed by nuxtJs, tailwinds css ,some markdown for guide/contribute/tutorial, is need more works but now is work,  i18n, darkmode and mobile by design here some screen:

**desktop:**
![screen-3](https://user-images.githubusercontent.com/66946113/142673376-37c8d59b-b63b-4338-b2a7-9091b79b7a20.png)
![screen-4](https://user-images.githubusercontent.com/66946113/142673387-29126565-286c-4f0d-ae07-1fb788d3ad1f.png)
![screen-5](https://user-images.githubusercontent.com/66946113/142673393-53e79fd5-db35-4d3f-8708-390b66a349c9.png) 
![screen-6](https://user-images.githubusercontent.com/66946113/142673397-0db790e0-8939-48e8-831d-106f13726433.png)
**mobile:**
![screen-1](https://user-images.githubusercontent.com/66946113/142673368-3d1ddfdd-3bba-43a7-a514-348c37c0af6e.png)
![screen-2](https://user-images.githubusercontent.com/66946113/142673373-212b39fe-db61-45c7-a162-a094d9125c69.png)

can i continue to work on ? cause you worked on new website here , thx

**Comment by xanimo** [comment]
This looks really cool but we're actually already in the process of a redesign. If you checkout my redesign branch you'll see the general skeleton of what we're working on and steps needed to complete. By all means you're free to continue working on it and submit for evaluation from the community though. :)

**Comment by tjstebbing** [comment]
We'll keep this in mind as inspiration for future updates, thanks!
