### ISSUE TITLE
parsing "never": invalid syntax

### ISSUE THREAD

**Issue by xanimo** [dogecoinfoundation/dogecoin.com#9]
not sure what happened but i'm encountering this error when running `hugo server`:

```
hugo server
Built in 10 ms
Error: Error building site: "/home/bluezr/source/repos/dogecoin.com-1/content/dogepedia/_index.md:1:1": 1 error(s) decoding:

* cannot parse 'Render' as bool: strconv.ParseBool: parsing "never": invalid syntax
```

https://github.com/dogecoinfoundation/dogecoin.com/blob/main/content/dogepedia/_index.md

**Comment by xanimo** [comment]
it appears my version of hugo got reverted to a version that didn't support this. my dev env is fixed with the help of @bellesea and @MishaBoar . Thank you!

**Comment by 7yl4r** [comment]
Do you have any information on what version of hugo did not support this and/or what version does?
