### ISSUE TITLE
Preview site front page rendering

### ISSUE THREAD

**Issue by lazybullfrog** [dogecoinfoundation/dogecoin.com#94]
Front page has some issues rendering. Brave browser, Chrome browser, Android 10 and 11, phone and other narrow viewports. 
![Screenshot_20220615-203155](https://user-images.githubusercontent.com/36180438/174007229-75297c1f-20c0-4a98-b429-a3ed0229ccc9.png)

**Comment by qlpqlp** [comment]
Fixed on the new PR that I will upload soon.
