### ISSUE TITLE
Suggestion: Added article introducing Dogecoin full node setup

### ISSUE THREAD

**Issue by Doge36588** [dogecoinfoundation/dogecoin.com#95]
1.What is the difference between a Dogecoin full node and a normal node?
2.The specific method of Dogecoin full node setup
3.How does running a Dogecoin core wallet contribute to the Dogecoin network?

**Comment by MishaBoar** [comment]
Hello, there is one already - please feel free to expand upon it, simplify, and amend it as needed:

https://github.com/dogecoinfoundation/dogecoin.com/blob/main/content/en/dogepedia/articles/what-is-a-node.md

**Comment by Doge36588** [comment]
Thanks for your reply!
