### ISSUE TITLE
Website Homepage UX Optimization

### ISSUE THREAD

**Issue by ritorhymes** [dogecoinfoundation/dogecoin.com#96]
1. Navigating the different wallet selections available was rather clunky in that the differing image sizes in the gallery caused the selection buttons and the screen to jump around when cycling through them instead of remaining static and consistent 

Here's an example of a screen record of that happening: 
https://drive.google.com/file/d/1TWD8qARVSFNtgTjoO0vqRspYcqD-mG3x/view?usp=drivesdk

2. There's a significantly large extra margin of empty space on the right side of the screen that the user can scroll off page towards that I see has no functional purpose and merely distracts from the intended experience scrolling through the content (that margin of empty space is basically almost half the size of the screen, contains no content and basically shows the main page being cut off) 

Here's an example of a screen record of that: 
https://drive.google.com/file/d/1TllpvQ5h-UpUlx6YOMNiloH5mgSt4RC1/view?usp=drivesdk

**Comment by qlpqlp** [comment]
Fixed on the latest version :)
